# rancherVersion: "v2.6.3"
# targets:
#   - charts
#   - systemCharts
# osType:
#   - linux
#   - windows
# chartsRepoUrl: "https://github.com/rancher/charts.git"
# chartsBranch: "dev-v2.6"
# systemChartsRepoUrl: "https://github.com/rancher/system-charts.git"
# systemChartsBranch: "dev-v2.6"
# systemChartsCommit: "74b11a0fd7b7b00034e926774fac7f57059631ec"

rancherTag: "v2.6.3"
targets:
  - charts
  - systemCharts
os:
  - linux
  - windows
charts:
  repository:
    location: "https://github.com/rancher/charts.git"
    branch: "dev-v2.6"
    commit: ""
systemcharts:
  repository:
    location: "https://github.com/rancher/charts.git"
    branch: "dev-v2.6"
    commit: ""
rke2:
  kdmData: "http://url/to/data.json"


rancherTag: "v0.0.0"
os:
  linux: true
  windows: true

core:
  enabled: true

rancher:
  enabled: true

charts:
  enabled: true
  repository:
    location: "https://github.com/rancher/charts.git"
    branch: "release-v2.6"
  monitoring:
    enabled: true
  istio:
    enabled: true

systemCharts:
  enabled: true
  repository:
    location: "https://github.com/rancher/charts.git"
    branch: "release-v2.6"
  monitoring:
    enabled: true
  istio:
    enabled: true

rke:
  enabled: true
  kdmData: "https://url/to/data.json"

rke2:
  enabled: true
  kdmData: "https://url/to/data.json"